### ISSUE TITLE
Convert JSON to JSON without a Java Bean

### ISSUE THREAD

**Issue by neoqing** [smooks/smooks#577]
I posted a question (https://github.com/smooks/smooks/issues/573) before, per @claudemamo suggestions, I tried with Freemarker, looks like it worked but not in my expected way.
Let me explain my requirements, we would like to convert one JSON in format A to a new JSON in format B, plus, we don't want to introduce any Java POJO in this process, for this purpose, I created a project (https://github.com/neoqing/smooks-samples)
I added two test cases, one of them has a JavaBean config (https://github.com/neoqing/smooks-samples/blob/ac335ca3f48a3d05e93c4f8202d10334191d1c80/src/test/java/com/neo/smooks/examples/TestSmooks.java#L16  ) and the other does not (https://github.com/neoqing/smooks-samples/blob/ac335ca3f48a3d05e93c4f8202d10334191d1c80/src/test/java/com/neo/smooks/examples/TestSmooks.java#L26) 
Based on the result, without a JavaBean, it does not work.
I'm wondering if my code is wrong or if Smooks doesn't support this requirement (convert JSON to JSON without a Java bean) at all.
Thanks in advance.

**Comment by claudemamo** [comment]
> Based on the result, without a JavaBean, it does not work.

It does not work because the FreeMarker template is referencing the JavaBean properties. Currently you have this template:

```ftl
{
  "orderNumber":${order.number},
  "orderStatus":"${order.status}",
  "creationDate":"${order.creationDate?date?string('yyyy-MM-dd')}"
} 
```
But the above template is referencing JavaBean properties, while in your `testJ2JWithoutJb` test, you must use a different template that references the _JSON keys_ like the one below: 
```ftl
{
  "orderNumber":${order.order_number},
  "orderStatus":"${order.order_status}",
  "creationDate":"${order.creation_date}"
}
```
Additionally, to conserve memory, Smooks doesn't retain the child events of the selected parent event unless explicitly configured to do so. In other words, the test will still fail because the child events (e.g., `order_number`) of the selected event (i.e., `order`) are discarded. There are couple ways of retaining the child events. Naively, you could retain all the events in memory like this:
```java
@Test
public void testJ2JWithoutJb() throws Exception {
   ...
   smooks.setFilterSettings(FilterSettings.newSaxNgSettings().setMaxNodeDepth(0));
   ...
```
This way of retaining events can be very inefficient because setting the max node depth to 0 means that all generated events are kept in memory. The [Smook fundamentals](https://www.smooks.org/v2/documentation/#fundamentals) and the [templating](https://www.smooks.org/v2/documentation/#templating) sections of the docs can guide you in implementing your solution the right way.
