### ISSUE TITLE
org.milyn.javabean.gen.ConfigGenerator null pointer issue

### ISSUE THREAD

**Issue by crognon** [smooks/smooks#86]
Hi all,

after some test to figure out how to use the fabulous smooks tool, I have to use it to populate Java from Json.

My java beans have many many properties so I was really happy when I have read about the ConfigGenerator to generate the configuration withs TODOS to map the right data. 

I have been trying to use  it but it keeps failing with a null pointer :+1: 

I use JDK 1.7
I have a jar with my beans
I have use -classpath to add Java;mylin-all.jar;myclasses.jar
I have set the -c rootClass providing the full qualified name
I have set -o someFile.xml to output the configuration

    > java -classpath C:\Java\jre\lib\rt.jar;milyn-smooks-all-1.5.1.jar;myClasses.jar  org.milyn.javabean.gen.ConfigGenerator -c  pkg1.pkg2.Class  -o smooks-pdc.xml
    Exception in thread "main" java.lang.NullPointerException
        at org.milyn.javabean.gen.ConfigGenerator.main(ConfigGenerator.java:72)

What could be wrong with my setup ? the line 72 in src is some mkdir action on a parent to the config file... I have tried to create the file beforehand but it changed nothing.
I have not found what I have been doing wrong or if there is some bug.

Thanks,
Cyril

**Comment by manish-in-java** [comment]
The configuration generator has the following code:

    String outputFileName = getArgument("-o", "Output File Path", true, args);
    File outputFile = new File(outputFileName);
    outputFile.getParentFile().mkdirs();

The issue description indicates that the tool was run on Microsoft Windows. When the tool is run on Windows, with a command line such as `-o file.xml`, `outputFile.getParentFile()` returns `null` (at least on JDK 1.6 and 1.7), because no directory has been specified with the file name. Using `-o ./file.xml` gets rid of the error.
