### ISSUE TITLE
Documentation not up to date. SmooksProcessor

### ISSUE THREAD

**Issue by blommish** [smooks/smooks#88]
http://www.smooks.org/mediawiki/index.php?title=V1.5:Smooks_v1.5_User_Guide#Apache_Camel_Integration

Smooks smooks = new Smooks("edi-to-xml-smooks-config.xml");
ExecutionContext context = smooks.createExecutionContext();
SmooksProcessor processor = new SmooksProcessor(smooks, context);

---

new SmooksProcessor wants a CamelContext, ExecutionContext does not work.

**Comment by jcordes73** [comment]
Well this has changed in the 1.6 release, but under http://www.smooks.org/mediawiki/index.php?title=User_Documentation I don't see documentation for 1.6.

@tfennelly Unfortunately it seems that the pages of smooks.org are not in this repo. How can we fix this?

**Comment by tfennelly** [comment]
@jcordes73, @blommish hi guys. These pages are in a MediaWiki database. Would be nice to port them all to MD, but that's a huge task at this stage since there are many pages (examples etc).

I can give access to edit MediaWiki so you guys can edit it if that helps? I closed the open access to that because of spam bots posting shit in it about Viagra etc :)

**Comment by saupan** [comment]
I cannot access the new documents at http://www.smooks.org/mediawiki/docs. How can I get access?
